<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>kma</string>
   </array>
  <key>name</key>
  <string>kuma</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.kuma</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.kuma</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.kuma</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.kuma</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\{|\}|\(|\)|\![^\=])</string>
          <key>name</key>
          <string>punctuation.kuma</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\!\=|\=|\+|\&amp;\&amp;|if)</string>
          <key>name</key>
          <string>keyword.operator.kuma</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false|null|\d+)</string>
          <key>name</key>
          <string>keyword.kuma</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?=\b\s?)(\w+)(?=\(.+\)|\!)</string>
          <key>name</key>
          <string>entity.name.function.kuma</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z]+)(?=([^a-zA-Z]*|\s+[a-zA-Z]+))(?!\(.+\))(?=([^\!]*)\=)</string>
          <key>name</key>
          <string>variable.kuma</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
